steps:
- uses: actions/checkout@v2
- uses: actions/setup-ruby@v1
  with:
    ruby-version: '2.x'
- name: Install Dependencies
  run: gem install foodcritic
- name: Run tests
  run: |
    foodcritic --version
    foodcritic --cookbook-path=examples/chef/cookbooks --rule-file=examples/chef/.foodcritic --epic-fail=any
